### ISSUE TITLE
I/O operation on closed file

### ISSUE THREAD

**Issue by innateessence** [jacquerie/flask-shell-ptpython#16]
I'm not sure what happened, seemingly out of nowhere whenever I exit the flask shell I get this error.

I've recreated the virtualenv and the issue started happening, so I modified my requirements.txt replacing all `>=` to `==` to force using the same pkg versions for the virtualenv before the issue started happening, and that didn't address the issue either.

This appears to still be very usable, so far it only happens when I exit the shell, although ~~I'm worried this may become a problem later on in the development cycle of my project.~~ this should be safe to ignore

```
flask-shell-ptpython==1.0.2
ptpython==3.0.18
prompt-toolkit==3.0.19
Flask==1.1.2
click==7.1.2
```

<details>
<summary>Traceback</summary>

$ flask shell
\> exit()
> Traceback (most recent call last):
```python
  File "PROJECT_DIR/venv/bin/flask", line 8, in <module>
    sys.exit(main())
  File "PROJECT_DIR/venv/lib/python3.9/site-packages/flask/cli.py", line 967, in main
    cli.main(args=sys.argv[1:], prog_name="python -m flask" if as_module else None)
  File "PROJECT_DIR/venv/lib/python3.9/site-packages/flask/cli.py", line 586, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "PROJECT_DIR/venv/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "PROJECT_DIR/venv/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "PROJECT_DIR/venv/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "PROJECT_DIR/venv/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "PROJECT_DIR/venv/lib/python3.9/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "PROJECT_DIR/venv/lib/python3.9/site-packages/flask/cli.py", line 426, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "PROJECT_DIR/venv/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "PROJECT_DIR/venv/lib/python3.9/site-packages/flask_shell_ptpython.py", line 37, in shell_command
    embed(globals=ctx)
  File "PROJECT_DIR/venv/lib/python3.9/site-packages/ptpython/repl.py", line 720, in embed
    repl.run()
  File "PROJECT_DIR/venv/lib/python3.9/site-packages/ptpython/repl.py", line 135, in run
    text = self.read()
  File "PROJECT_DIR/venv/lib/python3.9/site-packages/ptpython/python_input.py", line 1045, in read
    result = self.app.run(pre_run=pre_run, in_thread=True)
  File "PROJECT_DIR/venv/lib/python3.9/site-packages/prompt_toolkit/application/application.py", line 874, in run
    raise exception
  File "PROJECT_DIR/venv/lib/python3.9/site-packages/prompt_toolkit/application/application.py", line 855, in run_in_thread
    result = self.run(
  File "PROJECT_DIR/venv/lib/python3.9/site-packages/prompt_toolkit/application/application.py", line 891, in run
    return loop.run_until_complete(
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "PROJECT_DIR/venv/lib/python3.9/site-packages/prompt_toolkit/application/application.py", line 816, in run_async
    return await _run_async2()
  File "PROJECT_DIR/venv/lib/python3.9/site-packages/prompt_toolkit/application/application.py", line 792, in _run_async2
    result = await _run_async()
  File "PROJECT_DIR/venv/lib/python3.9/site-packages/prompt_toolkit/application/application.py", line 721, in _run_async
    with self.input.raw_mode(), self.input.attach(
  File "PROJECT_DIR/venv/lib/python3.9/site-packages/prompt_toolkit/input/vt100.py", line 129, in raw_mode
    return raw_mode(self.stdin.fileno())
ValueError: I/O operation on closed file
```
</details>

**Comment by innateessence** [comment]
```
ptpython
prompt-toolkit
```
These weren't explicitly specified in my virtualenvs requirements.txt, that may be the cause.

**Comment by innateessence** [comment]
This looks like a PtPython issue
https://github.com/prompt-toolkit/ptpython/issues/463

**Comment by innateessence** [comment]
Looks like it might be a prompt-toolkit issue.
https://github.com/prompt-toolkit/python-prompt-toolkit/issues/1456

**Comment by jonathanslenders** [comment]
Possible fix: https://github.com/prompt-toolkit/python-prompt-toolkit/pull/1457

edit: probably this is the only thing we really need: https://github.com/prompt-toolkit/ptpython/pull/466/files

**Comment by innateessence** [comment]
> Possible fix: https://github.com/prompt-toolkit/python-prompt-toolkit/pull/1457
> 
> edit: probably this is the only thing we really need: https://github.com/prompt-toolkit/ptpython/pull/466/files

Thanks for making the PR to fix it :)
